/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
const arbitrumContracts = {
  chainId: 42161,
  deploymentBlock: 454236303,
  StableToken: {
    address: "0xe002be6ff5cca4662f178972e092fa6b8428483f",
    abi: [
      {
        type: "constructor",
      },
      {
        type: "function",
        name: "allowance",
        inputs: [
          {
            name: "owner",
            type: "address",
          },
          {
            name: "spender",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "approve",
        inputs: [
          {
            name: "spender",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "balanceOf",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "burn",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "decimals",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "mint",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "name",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "owner",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "renounceOwnership",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "symbol",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "totalSupply",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "transfer",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferFrom",
        inputs: [
          {
            name: "from",
            type: "address",
          },
          {
            name: "to",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferOwnership",
        inputs: [
          {
            name: "newOwner",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "Approval",
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "spender",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Transfer",
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: true,
          },
          {
            name: "to",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
    ],
    inheritedFunctions: {},
  },
  ShakyToken: {
    address: "0x31c6e5ccc47fcf0886a889060147a74d896d9f5a",
    abi: [
      {
        type: "constructor",
      },
      {
        type: "function",
        name: "allowance",
        inputs: [
          {
            name: "owner",
            type: "address",
          },
          {
            name: "spender",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "approve",
        inputs: [
          {
            name: "spender",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "balanceOf",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "burn",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "decimals",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "mint",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "name",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "owner",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "renounceOwnership",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "symbol",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "totalSupply",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "transfer",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferFrom",
        inputs: [
          {
            name: "from",
            type: "address",
          },
          {
            name: "to",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferOwnership",
        inputs: [
          {
            name: "newOwner",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "Approval",
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "spender",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Transfer",
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: true,
          },
          {
            name: "to",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
    ],
    inheritedFunctions: {},
  },
  Collateral: {
    address: "0xc793991cb9d3dcbbbde5033d77c2aff170c3b96a",
    abi: [
      {
        type: "constructor",
        inputs: [
          {
            name: "name_",
            type: "string",
          },
          {
            name: "symbol_",
            type: "string",
          },
        ],
      },
      {
        type: "function",
        name: "STRIKE_DECIMALS",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "_claimForOption",
        inputs: [
          {
            name: "holder",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "uint256",
            name: "payout",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "_factory",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "_redeemPair",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "allowance",
        inputs: [
          {
            name: "owner",
            type: "address",
          },
          {
            name: "spender",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "approve",
        inputs: [
          {
            name: "spender",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "balanceOf",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "collDecimals",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "collateral",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "collateralData",
        outputs: [
          {
            type: "tuple",
            components: [
              {
                name: "address_",
                type: "address",
              },
              {
                name: "name",
                type: "string",
              },
              {
                name: "symbol",
                type: "string",
              },
              {
                name: "decimals",
                type: "uint8",
              },
            ],
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "consDecimals",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "consideration",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "considerationData",
        outputs: [
          {
            type: "tuple",
            components: [
              {
                name: "address_",
                type: "address",
              },
              {
                name: "name",
                type: "string",
              },
              {
                name: "symbol",
                type: "string",
              },
              {
                name: "decimals",
                type: "uint8",
              },
            ],
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "decimals",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "exercise",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
          {
            name: "caller",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "expirationDate",
        outputs: [
          {
            type: "uint40",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "factory",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "init",
        inputs: [
          {
            name: "collateral_",
            type: "address",
          },
          {
            name: "consideration_",
            type: "address",
          },
          {
            name: "expirationDate_",
            type: "uint40",
          },
          {
            name: "strike_",
            type: "uint256",
          },
          {
            name: "isPut_",
            type: "bool",
          },
          {
            name: "isEuro_",
            type: "bool",
          },
          {
            name: "oracle_",
            type: "address",
          },
          {
            name: "option_",
            type: "address",
          },
          {
            name: "factory_",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "isEuro",
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "isPut",
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "lock",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "locked",
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "mint",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "name",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "option",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "optionReserveRemaining",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "oracle",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "owner",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "redeem",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "redeem",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "redeem",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "redeemConsideration",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "renounceOwnership",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "reserveInitialized",
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "settle",
        inputs: [
          {
            name: "hint",
            type: "bytes",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "settlementPrice",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "strike",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "sweep",
        inputs: [
          {
            name: "holder",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "sweep",
        inputs: [
          {
            name: "holders",
            type: "address[]",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "symbol",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "toCollateral",
        inputs: [
          {
            name: "consAmount",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "toConsideration",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "toNeededConsideration",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "totalSupply",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "transfer",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferFrom",
        inputs: [
          {
            name: "from",
            type: "address",
          },
          {
            name: "to",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferOwnership",
        inputs: [
          {
            name: "newOwner",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "unlock",
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "Approval",
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "spender",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Initialized",
        inputs: [
          {
            name: "version",
            type: "uint64",
          },
        ],
      },
      {
        type: "event",
        name: "Redeemed",
        inputs: [
          {
            name: "option",
            type: "address",
          },
          {
            name: "token",
            type: "address",
          },
          {
            name: "holder",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Settled",
        inputs: [
          {
            name: "price",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Transfer",
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: true,
          },
          {
            name: "to",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
      {
        type: "error",
        name: "ArithmeticOverflow",
      },
      {
        type: "error",
        name: "ContractExpired",
      },
      {
        type: "error",
        name: "ContractNotExpired",
      },
      {
        type: "error",
        name: "EuropeanExerciseDisabled",
      },
      {
        type: "error",
        name: "FeeOnTransferNotSupported",
      },
      {
        type: "error",
        name: "InsufficientBalance",
      },
      {
        type: "error",
        name: "InsufficientCollateral",
      },
      {
        type: "error",
        name: "InsufficientConsideration",
      },
      {
        type: "error",
        name: "InvalidAddress",
      },
      {
        type: "error",
        name: "InvalidInitialization",
      },
      {
        type: "error",
        name: "InvalidValue",
      },
      {
        type: "error",
        name: "LockedContract",
      },
      {
        type: "error",
        name: "NoOracle",
      },
      {
        type: "error",
        name: "NonSettledOnly",
      },
      {
        type: "error",
        name: "NotInitializing",
      },
      {
        type: "error",
        name: "NotSettled",
      },
      {
        type: "error",
        name: "ReentrancyGuardReentrantCall",
      },
      {
        type: "error",
        name: "SafeERC20FailedOperation",
        inputs: [
          {
            name: "token",
            type: "address",
          },
        ],
      },
      {
        type: "error",
        name: "SettledOnly",
      },
    ],
    inheritedFunctions: {},
  },
  Option: {
    address: "0x881b632391ba4006a5ef296264cb7564e647f1ed",
    abi: [
      {
        type: "constructor",
        inputs: [
          {
            name: "name_",
            type: "string",
          },
          {
            name: "symbol_",
            type: "string",
          },
        ],
      },
      {
        type: "function",
        name: "allowance",
        inputs: [
          {
            name: "owner",
            type: "address",
          },
          {
            name: "spender",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "approve",
        inputs: [
          {
            name: "spender",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "balanceOf",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "balancesOf",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "tuple",
            components: [
              {
                name: "collateral",
                type: "uint256",
              },
              {
                name: "consideration",
                type: "uint256",
              },
              {
                name: "option",
                type: "uint256",
              },
              {
                name: "coll",
                type: "uint256",
              },
            ],
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "claim",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "claimFor",
        inputs: [
          {
            name: "holder",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "coll",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "collateral",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "consideration",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "decimals",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "details",
        outputs: [
          {
            type: "tuple",
            components: [
              {
                name: "option",
                type: "address",
              },
              {
                name: "coll",
                type: "address",
              },
              {
                name: "collateral",
                type: "tuple",
                components: [
                  {
                    name: "address_",
                    type: "address",
                  },
                  {
                    name: "name",
                    type: "string",
                  },
                  {
                    name: "symbol",
                    type: "string",
                  },
                  {
                    name: "decimals",
                    type: "uint8",
                  },
                ],
              },
              {
                name: "consideration",
                type: "tuple",
                components: [
                  {
                    name: "address_",
                    type: "address",
                  },
                  {
                    name: "name",
                    type: "string",
                  },
                  {
                    name: "symbol",
                    type: "string",
                  },
                  {
                    name: "decimals",
                    type: "uint8",
                  },
                ],
              },
              {
                name: "expiration",
                type: "uint256",
              },
              {
                name: "strike",
                type: "uint256",
              },
              {
                name: "isPut",
                type: "bool",
              },
              {
                name: "isEuro",
                type: "bool",
              },
              {
                name: "oracle",
                type: "address",
              },
            ],
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "exercise",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "exercise",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "expirationDate",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "factory",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "init",
        inputs: [
          {
            name: "coll_",
            type: "address",
          },
          {
            name: "owner_",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "isEuro",
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "isPut",
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "isSettled",
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "lock",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "mint",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "mint",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "name",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "oracle",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "owner",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "redeem",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "renounceOwnership",
        stateMutability: "pure",
      },
      {
        type: "function",
        name: "settle",
        inputs: [
          {
            name: "hint",
            type: "bytes",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "settlementPrice",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "strike",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "symbol",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "totalSupply",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "transfer",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferFrom",
        inputs: [
          {
            name: "from",
            type: "address",
          },
          {
            name: "to",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferOwnership",
        inputs: [
          {
            name: "newOwner",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "unlock",
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "Approval",
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "spender",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Claimed",
        inputs: [
          {
            name: "holder",
            type: "address",
            indexed: true,
          },
          {
            name: "optionBurned",
            type: "uint256",
          },
          {
            name: "collateralOut",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "ContractLocked",
      },
      {
        type: "event",
        name: "ContractUnlocked",
      },
      {
        type: "event",
        name: "Exercise",
        inputs: [
          {
            name: "longOption",
            type: "address",
          },
          {
            name: "holder",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Initialized",
        inputs: [
          {
            name: "version",
            type: "uint64",
          },
        ],
      },
      {
        type: "event",
        name: "Mint",
        inputs: [
          {
            name: "longOption",
            type: "address",
          },
          {
            name: "holder",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Settled",
        inputs: [
          {
            name: "price",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Transfer",
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: true,
          },
          {
            name: "to",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
      {
        type: "error",
        name: "ContractExpired",
      },
      {
        type: "error",
        name: "ContractNotExpired",
      },
      {
        type: "error",
        name: "EuropeanExerciseDisabled",
      },
      {
        type: "error",
        name: "InsufficientBalance",
      },
      {
        type: "error",
        name: "InvalidAddress",
      },
      {
        type: "error",
        name: "InvalidInitialization",
      },
      {
        type: "error",
        name: "InvalidValue",
      },
      {
        type: "error",
        name: "LockedContract",
      },
      {
        type: "error",
        name: "NoOracle",
      },
      {
        type: "error",
        name: "NotInitializing",
      },
      {
        type: "error",
        name: "ReentrancyGuardReentrantCall",
      },
    ],
    inheritedFunctions: {},
  },
  Factory: {
    address: "0x20e84883896c36b52f4cdefecca5f10140abf23d",
    abi: [
      {
        type: "constructor",
        inputs: [
          {
            name: "collClone_",
            type: "address",
          },
          {
            name: "optionClone_",
            type: "address",
          },
        ],
      },
      {
        type: "function",
        name: "COLL_CLONE",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "OPTION_CLONE",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "allowance",
        inputs: [
          {
            name: "token",
            type: "address",
          },
          {
            name: "owner_",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "approve",
        inputs: [
          {
            name: "token",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "approveOperator",
        inputs: [
          {
            name: "operator",
            type: "address",
          },
          {
            name: "approved",
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "approvedOperator",
        inputs: [
          {
            name: "owner_",
            type: "address",
          },
          {
            name: "operator",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "autoMintRedeem",
        inputs: [
          {
            name: "",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "blockToken",
        inputs: [
          {
            name: "token",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "blocklist",
        inputs: [
          {
            name: "",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "createOption",
        inputs: [
          {
            name: "collateral_",
            type: "address",
          },
          {
            name: "consideration_",
            type: "address",
          },
          {
            name: "expirationDate_",
            type: "uint40",
          },
          {
            name: "strike_",
            type: "uint96",
          },
          {
            name: "isPut_",
            type: "bool",
          },
        ],
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "createOption",
        inputs: [
          {
            name: "p",
            type: "tuple",
            components: [
              {
                name: "collateral",
                type: "address",
              },
              {
                name: "consideration",
                type: "address",
              },
              {
                name: "expirationDate",
                type: "uint40",
              },
              {
                name: "strike",
                type: "uint96",
              },
              {
                name: "isPut",
                type: "bool",
              },
              {
                name: "isEuro",
                type: "bool",
              },
              {
                name: "oracleSource",
                type: "address",
              },
              {
                name: "twapWindow",
                type: "uint32",
              },
            ],
          },
        ],
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "createOptions",
        inputs: [
          {
            name: "params",
            type: "tuple[]",
            components: [
              {
                name: "collateral",
                type: "address",
              },
              {
                name: "consideration",
                type: "address",
              },
              {
                name: "expirationDate",
                type: "uint40",
              },
              {
                name: "strike",
                type: "uint96",
              },
              {
                name: "isPut",
                type: "bool",
              },
              {
                name: "isEuro",
                type: "bool",
              },
              {
                name: "oracleSource",
                type: "address",
              },
              {
                name: "twapWindow",
                type: "uint32",
              },
            ],
          },
        ],
        outputs: [
          {
            type: "address[]",
            name: "result",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "enableAutoMintRedeem",
        inputs: [
          {
            name: "enabled",
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "isBlocked",
        inputs: [
          {
            name: "token",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "options",
        inputs: [
          {
            name: "",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "owner",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "renounceOwnership",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferFrom",
        inputs: [
          {
            name: "from",
            type: "address",
          },
          {
            name: "to",
            type: "address",
          },
          {
            name: "amount",
            type: "uint160",
          },
          {
            name: "token",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferOwnership",
        inputs: [
          {
            name: "newOwner",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "unblockToken",
        inputs: [
          {
            name: "token",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "Approval",
        inputs: [
          {
            name: "token",
            type: "address",
            indexed: true,
          },
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "AutoMintRedeemUpdated",
        inputs: [
          {
            name: "account",
            type: "address",
            indexed: true,
          },
          {
            name: "enabled",
            type: "bool",
          },
        ],
      },
      {
        type: "event",
        name: "OperatorApproval",
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "operator",
            type: "address",
            indexed: true,
          },
          {
            name: "approved",
            type: "bool",
          },
        ],
      },
      {
        type: "event",
        name: "OptionCreated",
        inputs: [
          {
            name: "collateral",
            type: "address",
            indexed: true,
          },
          {
            name: "consideration",
            type: "address",
            indexed: true,
          },
          {
            name: "expirationDate",
            type: "uint40",
          },
          {
            name: "strike",
            type: "uint96",
          },
          {
            name: "isPut",
            type: "bool",
          },
          {
            name: "isEuro",
            type: "bool",
          },
          {
            name: "oracle",
            type: "address",
          },
          {
            name: "option",
            type: "address",
            indexed: true,
          },
          {
            name: "coll",
            type: "address",
          },
        ],
      },
      {
        type: "event",
        name: "TokenBlocked",
        inputs: [
          {
            name: "token",
            type: "address",
          },
          {
            name: "blocked",
            type: "bool",
          },
        ],
      },
      {
        type: "error",
        name: "BlocklistedToken",
      },
      {
        type: "error",
        name: "EuropeanRequiresOracle",
      },
      {
        type: "error",
        name: "FailedDeployment",
      },
      {
        type: "error",
        name: "InsufficientAllowance",
      },
      {
        type: "error",
        name: "InsufficientBalance",
        inputs: [
          {
            name: "balance",
            type: "uint256",
          },
          {
            name: "needed",
            type: "uint256",
          },
        ],
      },
      {
        type: "error",
        name: "InvalidAddress",
      },
      {
        type: "error",
        name: "InvalidTokens",
      },
      {
        type: "error",
        name: "ReentrancyGuardReentrantCall",
      },
      {
        type: "error",
        name: "SafeERC20FailedOperation",
        inputs: [
          {
            name: "token",
            type: "address",
          },
        ],
      },
      {
        type: "error",
        name: "UnsupportedOracleSource",
      },
    ],
    inheritedFunctions: {},
  },
  YieldVault: {
    address: "0x88bc389f6218bf135168fc86ac818bd51a911b44",
    addresses: [
      "0x88bc389f6218bf135168fc86ac818bd51a911b44",
      "0xc989a1010f74afa4480056041ff8e0b9f2ccc75f",
    ],
    abi: [
      {
        type: "constructor",
        inputs: [
          {
            name: "collateral_",
            type: "address",
          },
          {
            name: "name_",
            type: "string",
          },
          {
            name: "symbol_",
            type: "string",
          },
          {
            name: "factory_",
            type: "address",
          },
        ],
      },
      {
        type: "function",
        name: "activeOptions",
        inputs: [
          {
            name: "",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "addOption",
        inputs: [
          {
            name: "option",
            type: "address",
          },
          {
            name: "spender",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "allowance",
        inputs: [
          {
            name: "owner",
            type: "address",
          },
          {
            name: "spender",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "approve",
        inputs: [
          {
            name: "spender",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "approveToken",
        inputs: [
          {
            name: "token",
            type: "address",
          },
          {
            name: "spender",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "asset",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "balanceOf",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "burn",
        inputs: [
          {
            name: "option",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "claimableRedeemRequest",
        inputs: [
          {
            name: "",
            type: "uint256",
          },
          {
            name: "controller",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "cleanupOptions",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "committed",
        inputs: [
          {
            name: "option",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "convertToAssets",
        inputs: [
          {
            name: "shares",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "convertToShares",
        inputs: [
          {
            name: "assets",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "decimals",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "deposit",
        inputs: [
          {
            name: "assets",
            type: "uint256",
          },
          {
            name: "receiver",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "enableAutoMintRedeem",
        inputs: [
          {
            name: "enabled",
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "execute",
        inputs: [
          {
            name: "target",
            type: "address",
          },
          {
            name: "data",
            type: "bytes",
          },
        ],
        outputs: [
          {
            type: "bytes",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "factory",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "fulfillRedeem",
        inputs: [
          {
            name: "controller",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "fulfillRedeems",
        inputs: [
          {
            name: "controllers",
            type: "address[]",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "getVaultStats",
        outputs: [
          {
            type: "uint256",
            name: "totalAssets_",
          },
          {
            type: "uint256",
            name: "totalShares_",
          },
          {
            type: "uint256",
            name: "idle_",
          },
          {
            type: "uint256",
            name: "committed_",
          },
          {
            type: "uint256",
            name: "utilizationBps_",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "idleCollateral",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "isOperator",
        inputs: [
          {
            name: "controller",
            type: "address",
          },
          {
            name: "operator",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "isValidSignature",
        inputs: [
          {
            name: "hash",
            type: "bytes32",
          },
          {
            name: "signature",
            type: "bytes",
          },
        ],
        outputs: [
          {
            type: "bytes4",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "maxDeposit",
        inputs: [
          {
            name: "",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "maxMint",
        inputs: [
          {
            name: "",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "maxRedeem",
        inputs: [
          {
            name: "controller",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "maxWithdraw",
        inputs: [
          {
            name: "",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "pure",
      },
      {
        type: "function",
        name: "mint",
        inputs: [
          {
            name: "shares",
            type: "uint256",
          },
          {
            name: "receiver",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "name",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "owner",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "pause",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "paused",
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "pendingRedeemRequest",
        inputs: [
          {
            name: "",
            type: "uint256",
          },
          {
            name: "controller",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "previewDeposit",
        inputs: [
          {
            name: "assets",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "previewMint",
        inputs: [
          {
            name: "shares",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "previewRedeem",
        inputs: [
          {
            name: "",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "pure",
      },
      {
        type: "function",
        name: "previewWithdraw",
        inputs: [
          {
            name: "",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "pure",
      },
      {
        type: "function",
        name: "redeem",
        inputs: [
          {
            name: "shares",
            type: "uint256",
          },
          {
            name: "receiver",
            type: "address",
          },
          {
            name: "controller",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
            name: "assets",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "redeemExpired",
        inputs: [
          {
            name: "option",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "removeOption",
        inputs: [
          {
            name: "option",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "renounceOwnership",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "requestRedeem",
        inputs: [
          {
            name: "shares",
            type: "uint256",
          },
          {
            name: "controller",
            type: "address",
          },
          {
            name: "owner",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "setOperator",
        inputs: [
          {
            name: "operator",
            type: "address",
          },
          {
            name: "approved",
            type: "bool",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "setupFactoryApproval",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "symbol",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "totalAssets",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "totalCommitted",
        outputs: [
          {
            type: "uint256",
            name: "total",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "totalSupply",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "transfer",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferFrom",
        inputs: [
          {
            name: "from",
            type: "address",
          },
          {
            name: "to",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferOwnership",
        inputs: [
          {
            name: "newOwner",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "unpause",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "utilizationBps",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "withdraw",
        inputs: [
          {
            name: "",
            type: "uint256",
          },
          {
            name: "",
            type: "address",
          },
          {
            name: "",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "pure",
      },
      {
        type: "event",
        name: "Approval",
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "spender",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Deposit",
        inputs: [
          {
            name: "sender",
            type: "address",
            indexed: true,
          },
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "assets",
            type: "uint256",
          },
          {
            name: "shares",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "OperatorSet",
        inputs: [
          {
            name: "controller",
            type: "address",
            indexed: true,
          },
          {
            name: "operator",
            type: "address",
            indexed: true,
          },
          {
            name: "approved",
            type: "bool",
          },
        ],
      },
      {
        type: "event",
        name: "OptionAdded",
        inputs: [
          {
            name: "option",
            type: "address",
            indexed: true,
          },
        ],
      },
      {
        type: "event",
        name: "OptionRemoved",
        inputs: [
          {
            name: "option",
            type: "address",
            indexed: true,
          },
        ],
      },
      {
        type: "event",
        name: "OptionsBurned",
        inputs: [
          {
            name: "option",
            type: "address",
            indexed: true,
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Paused",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
      },
      {
        type: "event",
        name: "RedeemRequest",
        inputs: [
          {
            name: "controller",
            type: "address",
            indexed: true,
          },
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "requestId",
            type: "uint256",
            indexed: true,
          },
          {
            name: "sender",
            type: "address",
          },
          {
            name: "shares",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Transfer",
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: true,
          },
          {
            name: "to",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Unpaused",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
      },
      {
        type: "event",
        name: "Withdraw",
        inputs: [
          {
            name: "sender",
            type: "address",
            indexed: true,
          },
          {
            name: "receiver",
            type: "address",
            indexed: true,
          },
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "assets",
            type: "uint256",
          },
          {
            name: "shares",
            type: "uint256",
          },
        ],
      },
      {
        type: "error",
        name: "AsyncOnly",
      },
      {
        type: "error",
        name: "ECDSAInvalidSignature",
      },
      {
        type: "error",
        name: "ECDSAInvalidSignatureLength",
        inputs: [
          {
            name: "length",
            type: "uint256",
          },
        ],
      },
      {
        type: "error",
        name: "ECDSAInvalidSignatureS",
        inputs: [
          {
            name: "s",
            type: "bytes32",
          },
        ],
      },
      {
        type: "error",
        name: "ERC4626ExceededMaxDeposit",
        inputs: [
          {
            name: "receiver",
            type: "address",
          },
          {
            name: "assets",
            type: "uint256",
          },
          {
            name: "max",
            type: "uint256",
          },
        ],
      },
      {
        type: "error",
        name: "ERC4626ExceededMaxMint",
        inputs: [
          {
            name: "receiver",
            type: "address",
          },
          {
            name: "shares",
            type: "uint256",
          },
          {
            name: "max",
            type: "uint256",
          },
        ],
      },
      {
        type: "error",
        name: "ERC4626ExceededMaxRedeem",
        inputs: [
          {
            name: "owner",
            type: "address",
          },
          {
            name: "shares",
            type: "uint256",
          },
          {
            name: "max",
            type: "uint256",
          },
        ],
      },
      {
        type: "error",
        name: "ERC4626ExceededMaxWithdraw",
        inputs: [
          {
            name: "owner",
            type: "address",
          },
          {
            name: "assets",
            type: "uint256",
          },
          {
            name: "max",
            type: "uint256",
          },
        ],
      },
      {
        type: "error",
        name: "EnforcedPause",
      },
      {
        type: "error",
        name: "ExpectedPause",
      },
      {
        type: "error",
        name: "InsufficientClaimable",
      },
      {
        type: "error",
        name: "InsufficientIdle",
      },
      {
        type: "error",
        name: "InvalidAddress",
      },
      {
        type: "error",
        name: "ReentrancyGuardReentrantCall",
      },
      {
        type: "error",
        name: "SafeERC20FailedOperation",
        inputs: [
          {
            name: "token",
            type: "address",
          },
        ],
      },
      {
        type: "error",
        name: "Unauthorized",
      },
      {
        type: "error",
        name: "WithdrawDisabled",
      },
      {
        type: "error",
        name: "ZeroAmount",
      },
    ],
    inheritedFunctions: {},
  },
} as const;
export default arbitrumContracts;
