name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Init foundry submodules
        run: |
          git -c url."https://github.com/".insteadOf="git@github.com:" \
            submodule update --init --recursive foundry/lib

      - name: Install foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Check formatting
        working-directory: foundry
        run: forge fmt --check

      - name: Build
        working-directory: foundry
        run: forge build

      - name: Test
        working-directory: foundry
        run: forge test
